import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | Rishi Terminal',
  description: 'The terms that govern use of Rishi Terminal.',
};

/**
 * Round-5 audit (finding 9): the sign-in page referenced a "Terms of
 * Service" that did not exist. This page states, factually and minimally,
 * what the product is and is not. It is written to match what the code
 * actually does — not aspirational legal boilerplate. (FD-13: founder to
 * have counsel review before paid tiers scale.)
 */
export default function TermsPage() {
  return (
    <main className="page-bg">
      <div className="page-content page-header" style={{ maxWidth: 760, margin: '0 auto', paddingBottom: 64 }}>
        <Link href="/" className="back-link">← Back to Rishi Terminal</Link>
        <h1 className="page-title" style={{ color: 'var(--accent-gold)' }}>Terms of Service</h1>
        <p style={{ fontSize: 12, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>Version 1 · effective October 2026</p>

        <div className="card-unified" style={{ padding: 24, marginTop: 24, display: 'grid', gap: 20 }}>
          <section>
            <h2 style={{ fontSize: 16, color: 'var(--accent-gold)', marginBottom: 8 }}>1. What this product is</h2>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Rishi Terminal is an educational research tool. It presents investment frameworks inspired by
              well-known investors, rendered as AI simulations that are fictional interpretations — not the real
              persons, not their views, and not their endorsements. The Rishi personas, their commentaries and
              their scores are generated by our software for education and illustration.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, color: 'var(--accent-gold)', marginBottom: 8 }}>2. Not investment advice</h2>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Nothing on this site is investment advice, a recommendation, or an offer to buy or sell any
              security. We are not a SEBI-registered investment adviser or research analyst. Scores, verdicts,
              &ldquo;Stock of the Day&rdquo;, &ldquo;Top Buys&rdquo; and &ldquo;Short Radar&rdquo; surfaces are
              outputs of deterministic models over datasets that are labelled per field as LIVE, REFERENCE or
              UNAVAILABLE — reference data is illustrative and not current. Verify everything from official
              sources and consult a SEBI-registered advisor before acting.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, color: 'var(--accent-gold)', marginBottom: 8 }}>3. Data accuracy</h2>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Live data, where shown, comes from public upstream providers (NSE India, Yahoo Finance,
              Screener.in, CoinGecko) and may be delayed or incomplete. Analytical values derived from our
              static reference datasets are illustrative placeholders. We label the provenance of displayed
              values, and where data is unavailable we show that state rather than a substitute number.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, color: 'var(--accent-gold)', marginBottom: 8 }}>4. Paid tiers and refunds</h2>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Paid tiers (Student, Disciple) are billed annually in INR via our payment provider and grant the
              features listed on the pricing page — features that do not exist are not listed. If a purchase
              fails to grant access, contact us and we will restore it or refund it. Beyond that, purchases are
              refundable within 7 days if the service has not met what the pricing page states.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, color: 'var(--accent-gold)', marginBottom: 8 }}>5. Acceptable use</h2>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Do not scrape, overload, or attempt to bypass access controls or rate limits. Your account is for
              your personal use. We may suspend accounts that abuse the service.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, color: 'var(--accent-gold)', marginBottom: 8 }}>6. Liability</h2>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              The service is provided &ldquo;as is&rdquo; without warranty of accuracy, availability or fitness
              for a particular purpose. To the maximum extent permitted by law, our liability for any claim
              arising from use of the service is limited to the amount you paid us in the 12 months before the
              claim.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
